version: "3.3"
services:
  kylin-api:
    # image: kylinnetwork/kylin-api:latest
    build: .
    depends_on:
      - postgres
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:postgres@postgres/kylin_parachain
    ports:
      - "8080:8080"
    restart: always
    container_name: kylin-api
    volumes:
      - ./api:/app/api
      - ./wsgi.py:/app/wsgi.py
      - ./bin:/app/bin
  postgres:
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kylin_parachain
    image: postgres:13.2
    ports:
      - 5433:5432
    restart: always
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./schemas.sql:/docker-entrypoint-initdb.d/schemas.sql
  postgres-backups:
    image: prodrigestivill/postgres-backup-local
    depends_on:
      - postgres
    restart: always
    user: postgres:postgres
    container_name: postgres-backups
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kylin_parachain
      SCHEDULE: "@every 30m"
      HEALTHCHECK_PORT: 8080
    volumes:
      - ./postgres-backups:/backups
volumes:
  app:
  postgres-data:
  postgres_backups:
