version: "3.3"
services:
  kylin-api:
    build: .
    depends_on:
      - postgres
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:postgres@postgres/kylin_parachain
    ports:
      - "8080:8080"
    restart: always
    container_name: kylin-api
    volumes:
      - ./api:/app/api
      - ./wsgi.py:/app/wsgi.py
      - ./bin:/app/bin
  postgres:
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kylin_parachain
    image: postgres:13
    ports:
      - 5433:5432
    restart: always
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./schemas.sql:/docker-entrypoint-initdb.d/schemas.sql
  postgres-backups:
    image: eeshugerman/postgres-backup-s3:13
    depends_on:
      - postgres
    restart: always
    container_name: postgres-backups
    environment:
      SCHEDULE: '@every 30m'
      S3_REGION: ${KYLIN_API_S3_REGION}
      S3_ACCESS_KEY_ID: ${KYLIN_API_S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${KYLIN_API_S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${KYLIN_API_S3_BUCKET}
      S3_PREFIX: kylin_parachain_backups
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: kylin_parachain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  app:
  postgres-data: