version: "3.3"
services:
  kylin-api:
    # image: kylinnetwork/kylin-api:latest
    build: .
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:postgres@db/kylin_parachain
    ports:
      - "8080:8080"
    restart: always
    container_name: kylin-api
    volumes:
      - ./api:/app/api
      - ./wsgi.py:/app/wsgi.py
      - ./bin:/app/bin
  db:
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kylin_parachain
    image: postgres:latest
    ports:
      - 5433:5432
    restart: always
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./schemas.sql:/docker-entrypoint-initdb.d/schemas.sql
volumes:
  app:
  postgres-data: